### ISSUE TITLE
SAC File Error

### ISSUE THREAD

**Issue by napatt2** [AI4EPS/PhaseNet#79]
Hi, I run the batch prediction using the given sample dataset. However, I could not get the results and it shows the following error. Thanks in advance.

`!python phasenet/predict.py --model=model/190703-214543 --data_list=test_data/sac.csv --data_dir=test_data/sac --format=sac --batch_size=1 --plot_figure`

```
2023-10-12 01:42:58.291230: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-12 01:42:59.522726: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2023-10-12 01:43:01,804 Pred log: results
2023-10-12 01:43:01,804 Dataset size: 16
2023-10-12 01:43:01,931 Model: depths 5, filters 8, filter size 7x1, pool size: 4x1, dilation rate: 1x1
2023-10-12 01:43:04.480757: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
2023-10-12 01:43:04,753 restoring model model/190703-214543/model_95.ckpt
Pred:   0% 0/16 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/content/PhaseNet/phasenet/predict.py", line 262, in <module>
    main(args)
  File "/content/PhaseNet/phasenet/predict.py", line 255, in main
    pred_fn(args, data_reader, log_dir=args.result_dir)
  File "/content/PhaseNet/phasenet/predict.py", line 154, in pred_fn
    df = df[
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 3813, in __getitem__
    indexer = self.columns._get_indexer_strict(key, "columns")[1]
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6070, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/base.py", line 6133, in _raise_if_missing
    raise KeyError(f"{not_found} not in index")
KeyError: "['phase_amplitude'] not in index"
```

**Comment by napatt2** [comment]
It works now after I changed my code to:

`python phasenet/predict.py --model=model/190703-214543 --data_list=test_data/sac.csv --data_dir=test_data/sac --format=sac --amplitude --response_xml=test_data/stations.xml --batch_size=1 --sampling_rate=100 --plot_figure`

**Comment by napatt2** [comment]
However, I still wondered what is the problem of my previous code. Please kindly advise on this. Any helps would be appreciated.

**Comment by zhuwq0** [comment]
Hi, adding the --amplitude argument should fix the error.
